language: ruby
cache: bundler
rvm:
- 2.3.8
- 2.4.6
- 2.5.5
- 2.6.3
before_install:
- gem install bundler -v 2.0.2
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build
- export RUBY_VERSION=$(echo $RUBY_VERSION | sed 's/ruby-//')
install:
- bundle install
- bundle exec rake gem:install
script:
- rum
after_script:
- ./cc-test-reporter after-build --exit-code ${TRAVIS_TEST_RESULT}
