name: Rum
on:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
        - 2.4.x
        - 2.5.x
        - 2.6.x
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Rum
      run: |
        gem install bundler -v 2.0.2
        bundle install --jobs 4 --retry 3
        bundle exec rake gem:install
        rum
